language: python
python:
  - "2.7"
  - "3.4"
sudo: true
addons:
  apt:
    packages:
        - libatlas-dev 
        - libatlas-base-dev 
        - liblapack-dev
        - libproj-dev
        - gfortran
        - gdal-bin
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy gdal
install:
  - travis_retry pip install pylint pep8
  - travis_retry pip install -r requirements.txt
script: 
    - pep8 eodatasets --max-line-length 120
    - pylint eodatasets --reports no
    - py.test eodatasets tests 
cache: apt
