language: python
python:
  - "2.7"
  - "3.4"
sudo: true
addons:
  apt:
    packages:
        - libatlas-dev 
        - libatlas-base-dev 
        - liblapack-dev
        - libproj-dev
        - gfortran
        - gdal-bin
        - libgdal1-dev
install:
  # Expand include path for building python-gdal bindings.
  - export CPLUS_INCLUDE_PATH="/usr/include/gdal"
  - export C_INCLUDE_PATH="/usr/include/gdal"
  # GDAL python version must match system libgdal version.
  - travis_retry pip install pylint pep8 GDAL==1.10.0
  - travis_retry pip install -r requirements.txt
script: 
    - pep8 eodatasets --max-line-length 120
    - pylint eodatasets --reports no
    - py.test eodatasets tests --runslow -m 'not slow'
    - py.test eodatasets tests --runslow -m 'slow'
cache: apt
